name: Build

on:
  workflow_dispatch:
  push:
    # disable triggering for the following paths and files
    paths-ignore:
#      - '.github/**'
      - '.gitignore'
      - 'README.md'
      - 'docs/**'


defaults:
  run:
    shell: bash

jobs:
  branch_build:
    name: Branch Build for ${{ matrix.runner }}

    if: ${{ github.ref != 'refs/heads/main' }}

    runs-on: ${{ matrix.runner }}

    permissions: write-all

    strategy:
      matrix:
#        runner: [ ubuntu-22.04, macos-14-large, macos-14-xlarge ]
        runner: [ macos-14-large ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        id: checkout-source


      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          version: '22.36.1'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          native-image-pr-reports: 'true'


      - name: Echo step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          

      - name: Build native image
        run: |
          mvn -e -DskipTests=true -Pnative clean package

