name: Build

on:
  workflow_dispatch:
  push:
    # disable triggering for the following paths and files
    paths-ignore:
#      - '.github/**'
      - '.gitignore'
      - 'README.md'
      - 'docs/**'


defaults:
  run:
    shell: bash

jobs:
  branch_build:
    name: Branch Build for ${{ matrix.profile.runner }}

    if: ${{ github.ref != 'refs/heads/main' }}

    runs-on: ${{ matrix.profile.runner }}

    permissions: write-all

    strategy:
      matrix:
        java-version: ['21']
        profile: [
          {
            runner: ubuntu-22.04,
            platform: x86_64,
            os: linux
          },
          {
            runner: macos-13,
            platform: x86_64,
            os: darwin
          },
          {
            runner: macos-14,
            platform: arm64,
            os: darwin
          }
        ]


#        include:
#          - runner: ubuntu-22.04
#            platform: x86_64
#            os: linux
#          - runner: macos-13
#            platform: x86_64
#            os: darwin
#          - runner: macos-14
#            platform: arm64
#            os: darwin

#        runner: [ ubuntu-22.04, macos-13, macos-14 ]
#        runner: [ ubuntu-22.04 ]

    steps:
      - name: Echo
        run: |
          uname -a

      - name: Checkout source
        uses: actions/checkout@v4
        id: checkout-source


      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'graalvm'
          version: '22.36.1'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          native-image-pr-reports: 'true'


      - name: Echo step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          

      - name: Build native image
        run: |
          mvn -e -DskipTests=true -Pnative clean package


      - name: Rename executable
        run: |
          mkdir -p artifacts
          cp target/demo-native artifacts/demo-native-${{ matrix.profile.platform }}-${{ matrix.profile.os }}
          ls -l artifacts
          
          
